//! AI Architect with LLM Integration
//!
//! Provides intelligent route design using Cohere's LLM with tool calling.

use std::sync::Arc;
use tokio::sync::RwLock;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use tracing::{debug, info, warn};

use crate::cohere_llm::{CohereLlm, ToolDefinition, ToolCall, ChatMessage, LlmError};
use crate::rhai_engine::RhaiEngine;
use crate::vector_store::VectorStore;

/// AI Architect errors
#[derive(Debug, Error)]
pub enum AiArchitectError {
    #[error("LLM error: {0}")]
    LlmError(String),

    #[error("Tool execution error: {0}")]
    ToolError(String),

    #[error("Validation error: {0}")]
    ValidationError(String),
}

impl From<LlmError> for AiArchitectError {
    fn from(e: LlmError) -> Self {
        AiArchitectError::LlmError(e.to_string())
    }
}

/// Tool execution result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    pub name: String,
    pub success: bool,
    pub message: String,
    pub data: Option<serde_json::Value>,
}

/// Route configuration generated by the AI
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedRoute {
    pub path: String,
    pub method: String,
    pub upstream: String,
    pub transform_script: Option<String>,
    pub description: String,
}

/// AI Architect for intelligent route design
pub struct AiArchitect {
    llm: CohereLlm,
    rhai_engine: Arc<RhaiEngine>,
    vector_store: Arc<RwLock<VectorStore>>,
    history: Vec<ChatMessage>,
    tools: Vec<ToolDefinition>,
}

impl AiArchitect {
    /// Create a new AI Architect
    pub fn new(
        rhai_engine: Arc<RhaiEngine>,
        vector_store: Arc<RwLock<VectorStore>>,
    ) -> Self {
        let llm = CohereLlm::new();
        let tools = Self::build_tool_definitions();

        Self {
            llm,
            rhai_engine,
            vector_store,
            history: Vec::new(),
            tools,
        }
    }

    /// Check if LLM is available
    pub fn is_available(&self) -> bool {
        self.llm.is_available()
    }

    /// Build tool definitions for the LLM
    fn build_tool_definitions() -> Vec<ToolDefinition> {
        vec![
            ToolDefinition {
                name: "deploy_route".to_string(),
                description: "Deploy a new integration route to the gateway. Use this when the user wants to create a route that connects services.".to_string(),
                parameter_definitions: serde_json::json!({
                    "path": {
                        "type": "string",
                        "description": "The URL path for the route (e.g., /api/users)",
                        "required": true
                    },
                    "method": {
                        "type": "string",
                        "description": "HTTP method (GET, POST, PUT, DELETE)",
                        "required": true
                    },
                    "upstream": {
                        "type": "string",
                        "description": "The upstream service URL to forward requests to",
                        "required": true
                    },
                    "transform_script": {
                        "type": "string",
                        "description": "Optional Rhai script for data transformation",
                        "required": false
                    }
                }),
            },
            ToolDefinition {
                name: "lookup_schema".to_string(),
                description: "Search for API endpoints in the knowledge base. Use this to find existing APIs that match a user's requirements.".to_string(),
                parameter_definitions: serde_json::json!({
                    "query": {
                        "type": "string",
                        "description": "Search query describing the API to find",
                        "required": true
                    },
                    "limit": {
                        "type": "integer",
                        "description": "Maximum number of results (default: 5)",
                        "required": false
                    }
                }),
            },
            ToolDefinition {
                name: "validate_script".to_string(),
                description: "Validate a Rhai transformation script before deployment. Returns validation errors if any.".to_string(),
                parameter_definitions: serde_json::json!({
                    "script": {
                        "type": "string",
                        "description": "The Rhai script to validate",
                        "required": true
                    }
                }),
            },
        ]
    }

    /// Get the system prompt for the architect
    fn system_prompt(&self) -> String {
        r#"You are the Naseej Architect, an AI assistant that helps design and deploy integration routes.

Your capabilities:
1. **deploy_route**: Create new routes that connect services
2. **lookup_schema**: Search for existing API definitions
3. **validate_script**: Check Rhai transformation scripts

When a user asks to create an integration:
1. Understand their requirements
2. Use lookup_schema if they reference existing APIs
3. Use validate_script if a transformation is needed
4. Use deploy_route to create the final route

For transformations, use Rhai scripting. Example:
```rhai
// Transform JSON payload
let data = ctx.body;
data.timestamp = now_utc();
ctx.body = data;
```

Always explain what you're doing and confirm with the user before deploying."#.to_string()
    }

    /// Process a user message and return a response
    pub async fn chat(&mut self, message: &str) -> Result<String, AiArchitectError> {
        // Add user message to history
        self.history.push(ChatMessage {
            role: "user".to_string(),
            content: message.to_string(),
        });

        if !self.llm.is_available() {
            // Fallback to simple pattern matching
            return self.fallback_response(message).await;
        }

        // Call LLM with tools
        let (response, tool_calls) = self.llm
            .chat_with_tools(
                message,
                Some(&self.system_prompt()),
                &self.history[..self.history.len() - 1], // Exclude current message
                &self.tools,
            )
            .await?;

        // Execute any tool calls
        let mut tool_results = Vec::new();
        for call in tool_calls {
            let result = self.execute_tool(&call).await;
            tool_results.push(result);
        }

        // Build final response
        let final_response = if tool_results.is_empty() {
            response
        } else {
            let tool_summary: String = tool_results
                .iter()
                .map(|r| {
                    if r.success {
                        format!("✅ {}: {}", r.name, r.message)
                    } else {
                        format!("❌ {}: {}", r.name, r.message)
                    }
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!("{}\n\n**Actions taken:**\n{}", response, tool_summary)
        };

        // Add assistant response to history
        self.history.push(ChatMessage {
            role: "assistant".to_string(),
            content: final_response.clone(),
        });

        Ok(final_response)
    }

    /// Execute a tool call
    async fn execute_tool(&self, call: &ToolCall) -> ToolResult {
        match call.name.as_str() {
            "deploy_route" => self.execute_deploy_route(&call.parameters).await,
            "lookup_schema" => self.execute_lookup_schema(&call.parameters).await,
            "validate_script" => self.execute_validate_script(&call.parameters),
            _ => ToolResult {
                name: call.name.clone(),
                success: false,
                message: format!("Unknown tool: {}", call.name),
                data: None,
            },
        }
    }

    /// Execute deploy_route tool
    async fn execute_deploy_route(&self, params: &serde_json::Value) -> ToolResult {
        let path = params.get("path").and_then(|v| v.as_str()).unwrap_or("");
        let method = params.get("method").and_then(|v| v.as_str()).unwrap_or("GET");
        let upstream = params.get("upstream").and_then(|v| v.as_str()).unwrap_or("");
        let transform_script = params.get("transform_script").and_then(|v| v.as_str());

        if path.is_empty() || upstream.is_empty() {
            return ToolResult {
                name: "deploy_route".to_string(),
                success: false,
                message: "Missing required parameters: path and upstream".to_string(),
                data: None,
            };
        }

        // Validate transform script if provided
        if let Some(script) = transform_script {
            let validation = self.rhai_engine.validate(script);
            if !validation.valid {
                return ToolResult {
                    name: "deploy_route".to_string(),
                    success: false,
                    message: format!("Transform script validation failed: {:?}", validation.errors),
                    data: None,
                };
            }
        }

        let route = GeneratedRoute {
            path: path.to_string(),
            method: method.to_uppercase(),
            upstream: upstream.to_string(),
            transform_script: transform_script.map(String::from),
            description: format!("{} {} -> {}", method.to_uppercase(), path, upstream),
        };

        info!(path = %route.path, upstream = %route.upstream, "Route configured by AI");

        ToolResult {
            name: "deploy_route".to_string(),
            success: true,
            message: format!("Route configured: {} {} -> {}", route.method, route.path, route.upstream),
            data: Some(serde_json::to_value(&route).unwrap()),
        }
    }

    /// Execute lookup_schema tool
    async fn execute_lookup_schema(&self, params: &serde_json::Value) -> ToolResult {
        let query = params.get("query").and_then(|v| v.as_str()).unwrap_or("");
        let limit = params.get("limit").and_then(|v| v.as_u64()).unwrap_or(5) as usize;

        if query.is_empty() {
            return ToolResult {
                name: "lookup_schema".to_string(),
                success: false,
                message: "Missing required parameter: query".to_string(),
                data: None,
            };
        }

        let store = self.vector_store.read().await;
        match store.search(query, limit).await {
            Ok(results) => {
                let msg = if results.is_empty() {
                    format!("No APIs found matching '{}'", query)
                } else {
                    format!("Found {} API(s) matching '{}'", results.len(), query)
                };

                ToolResult {
                    name: "lookup_schema".to_string(),
                    success: true,
                    message: msg,
                    data: Some(serde_json::to_value(&results).unwrap()),
                }
            }
            Err(e) => ToolResult {
                name: "lookup_schema".to_string(),
                success: false,
                message: format!("Search failed: {:?}", e),
                data: None,
            },
        }
    }

    /// Execute validate_script tool
    fn execute_validate_script(&self, params: &serde_json::Value) -> ToolResult {
        let script = params.get("script").and_then(|v| v.as_str()).unwrap_or("");

        if script.is_empty() {
            return ToolResult {
                name: "validate_script".to_string(),
                success: false,
                message: "Missing required parameter: script".to_string(),
                data: None,
            };
        }

        let validation = self.rhai_engine.validate(script);

        ToolResult {
            name: "validate_script".to_string(),
            success: validation.valid,
            message: if validation.valid {
                "Script is valid".to_string()
            } else {
                format!("Validation errors: {:?}", validation.errors)
            },
            data: Some(serde_json::to_value(&validation).unwrap()),
        }
    }

    /// Fallback response when LLM is not available
    async fn fallback_response(&mut self, message: &str) -> Result<String, AiArchitectError> {
        let lower = message.to_lowercase();

        let response = if lower.contains("deploy") || lower.contains("create") || lower.contains("route") {
            "I can help you create a route! However, the AI service (COHERE_API_KEY) is not configured.\n\n\
            To create a route manually, you can use the API:\n\
            ```json\n\
            POST /api/routes\n\
            {\n\
              \"path\": \"/your-path\",\n\
              \"method\": \"GET\",\n\
              \"upstream\": \"http://your-service\"\n\
            }\n\
            ```\n\n\
            Set COHERE_API_KEY to enable AI-powered route generation.".to_string()
        } else if lower.contains("help") {
            "I'm the Naseej Architect - I help design integration routes.\n\n\
            **Available commands:**\n\
            - *Create a route* - Design new integrations\n\
            - *Find APIs* - Search knowledge base\n\
            - *Validate script* - Check Rhai scripts\n\n\
            Note: Full AI capabilities require COHERE_API_KEY.".to_string()
        } else {
            "I'm ready to help you design integration routes! Tell me what services you want to connect.\n\n\
            Note: Set COHERE_API_KEY for full AI capabilities.".to_string()
        };

        self.history.push(ChatMessage {
            role: "assistant".to_string(),
            content: response.clone(),
        });

        Ok(response)
    }

    /// Clear conversation history
    pub fn clear_history(&mut self) {
        self.history.clear();
        info!("Architect conversation history cleared");
    }

    /// Get conversation history
    pub fn history(&self) -> &[ChatMessage] {
        &self.history
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_fallback_response() {
        let rhai = Arc::new(RhaiEngine::new());
        let store = Arc::new(RwLock::new(VectorStore::new()));
        let mut architect = AiArchitect::new(rhai, store);

        let response = architect.chat("help").await.unwrap();
        assert!(response.contains("Naseej Architect"));
    }

    #[test]
    fn test_tool_definitions() {
        let tools = AiArchitect::build_tool_definitions();
        assert_eq!(tools.len(), 3);
        assert!(tools.iter().any(|t| t.name == "deploy_route"));
    }
}
